# Generated by Django 4.0.5 on 2022-07-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blogcomment_author_blog_cover_blogcomment_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
